Sharpshooter/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sharpshooter.Models
{
    public class Menu
    {
        [Key]
        public int MenuID { get; set; }

        [Display(Name ="Menu Title")]
        public string MenuTitle { get; set; }

        [Display(Name ="Description")]
        public string MenuDescription { get; set; }

        public virtual List<MenuItem> MenuItems { get; set; }

        public virtual List<MenuGroup> MenuGroups { get; set; }
    }
}

Sharpshooter/Controllers/MenuGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class MenuGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MenuGroups
        public ActionResult Index()
        {
            var menuGroups = db.MenuGroups.Include(m => m.Menu);
            return View(menuGroups.ToList());
        }

        public ActionResult ViewMenuGroups()
        {
            var menuGroups = db.MenuGroups.Include(m => m.Menu);
            return View(menuGroups.ToList());
        }

        // GET: MenuGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            return View(menuGroup);
        }

        // GET: MenuGroups/Create
        public ActionResult Create()
        {
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle");
            return View();
        }

        // POST: MenuGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuGroupID,MenuID,MenuGroupTitle,MenuGroupDescription")] MenuGroup menuGroup)
        {
            if (ModelState.IsValid)
            {
                db.MenuGroups.Add(menuGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // GET: MenuGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // POST: MenuGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuGroupID,MenuID,MenuGroupTitle,MenuGroupDescription")] MenuGroup menuGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menuGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // GET: MenuGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            return View(menuGroup);
        }

        // POST: MenuGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            db.MenuGroups.Remove(menuGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class MenusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menus
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        public ActionResult ViewMenuAll()
        {
            var categories = db.Menus.ToList();
            return View(categories);
        }


        public ActionResult Browse(string category)
        {
            var categoryModel = db.Menus.Include("MenuItems").Single(c => c.MenuTitle == category);
            return View(categoryModel);
            
        }
        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        public ActionResult ViewItems(int id)
        {
            MenuItem menuItem = new MenuItem();
            menuItem = db.MenuItems.Where(x => x.MenuItemID == id).FirstOrDefault();
            
            return View(menuItem);
        }

        public ActionResult ViewMenu(int id)
        {
            var Item = db.MenuItems.Find(id);
            return View(Item);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuID,MenuTitle,MenuDescription")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuID,MenuTitle,MenuDescription")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;
using Sharpshooter.ViewModel;

namespace Sharpshooter.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var addedItem = db.MenuItems
                .Single(item => item.MenuItemID == id);

            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            string itemName = db.Carts
                .Single(item => item.RecordId == id).MenuItem.MenuItemTitle;

            int itemCount = cart.RemoveFromCart(id);

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Sharpshooter/Views/Menus/Browse.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Browse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Browsing Category: @Model.MenuTitle</h2>

<ul>
    @foreach(var item in Model.MenuItems)
    {
        <li>
            @Html.ActionLink(item.MenuItemTitle, "ViewItems",new { id=item.MenuItemID})
        </li>
    }
</ul>

Sharpshooter/Views/Menus/Create.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MenuTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharpshooter/Views/Menus/Delete.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sharpshooter/Views/Menus/Details.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MenuID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sharpshooter/Views/Menus/Edit.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenuID)

        <div class="form-group">
            @Html.LabelFor(model => model.MenuTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharpshooter/Views/Menus/Index.cshtml
@model IEnumerable<Sharpshooter.Models.Menu>

@{
    ViewBag.Title = "Admin Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Menu</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MenuTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MenuID }) |
            @Html.ActionLink("Details", "Details", new { id = item.MenuID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.MenuID }) |
            @Html.ActionLink("View Menu", "ViewMenu", new { id = item.MenuID })
        </td>
    </tr>
}

</table>

<p>
    <li>@Html.ActionLink("Menu Groups", "Index", "MenuGroups")</li>
</p>

Sharpshooter/Views/Menus/ViewItems.cshtml
@model Sharpshooter.Models.MenuItem

@{ 
    ViewBag.Title = "Item - " + Model.MenuItemTitle;
}

<h2>@Model.MenuItemTitle</h2>

<p>
    <img src="@Url.Content(Model.MenuItemImg)" width="255" height="195"/>
</p>

<div>
    <p>
        <em>Category: </em> @Model.MenuGroup.MenuGroupTitle
    </p>

    <p>
        <em>Description:</em> @Model.MenuItemDescription
    </p>
    <p>
        <em>Ingredients: </em> @Model.MenuItemIngredients
    </p>
    <p>
        <em>Price: </em> @String.Format("{0:F}",Model.MenuItemCost)
    </p>

    <p>
        @Html.ActionLink("Add To Cart", "AddToCart","ShoppingCart", new { id = Model.MenuItemID}, "" )
    </p>
</div>
<p>
    @Html.ActionLink("Back to Full Menu", "ViewMenuAll")
</p>

Sharpshooter/Views/Menus/ViewMenu.cshtml
@model IEnumerable<Sharpshooter.Models.Menu>

@{
    ViewBag.Title = "ViewMenu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Browse Category</h2>
<p>
    Select from @Model.Count()
    genres:
</p>
<ul>
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.MenuTitle, "Browse", new { category = category.MenuTitle })</li>
    }
</ul>

Sharpshooter/Views/Menus/ViewMenuAll.cshtml
@model IEnumerable<Sharpshooter.Models.Menu>

@{
    ViewBag.Title = "ViewMenuAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Browse Category</h2>
<p>
    Select from @Model.Count()
    genres:
</p>
<ul>
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.MenuTitle,"Browse",new { category = category.MenuTitle })</li>
    }
</ul>