Sharpshooter/Models/MenuGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sharpshooter.Models
{
    public class MenuGroup
    {
        [Key]
        public int MenuGroupID { get; set; }

        [ForeignKey("Menu")]
        public int MenuID { get; set; }
        public virtual Menu Menu { get; set; }


        [Required(ErrorMessage ="A title is required for the menu group")]
        [Display(Name =" Menu Group Name")]
        public string MenuGroupTitle { get; set; }

        [Display(Name ="Description")]
        public string MenuGroupDescription { get; set; }
    }
}

Sharpshooter/Controllers/MenuGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class MenuGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MenuGroups
        public ActionResult Index()
        {
            var menuGroups = db.MenuGroups.Include(m => m.Menu);
            return View(menuGroups.ToList());
        }

        public ActionResult ViewMenuGroups()
        {
            var menuGroups = db.MenuGroups.Include(m => m.Menu);
            return View(menuGroups.ToList());
        }

        // GET: MenuGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            return View(menuGroup);
        }

        // GET: MenuGroups/Create
        public ActionResult Create()
        {
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle");
            return View();
        }

        // POST: MenuGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuGroupID,MenuID,MenuGroupTitle,MenuGroupDescription")] MenuGroup menuGroup)
        {
            if (ModelState.IsValid)
            {
                db.MenuGroups.Add(menuGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // GET: MenuGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // POST: MenuGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuGroupID,MenuID,MenuGroupTitle,MenuGroupDescription")] MenuGroup menuGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menuGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuGroup.MenuID);
            return View(menuGroup);
        }

        // GET: MenuGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            if (menuGroup == null)
            {
                return HttpNotFound();
            }
            return View(menuGroup);
        }

        // POST: MenuGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuGroup menuGroup = db.MenuGroups.Find(id);
            db.MenuGroups.Remove(menuGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;
using System.IO;

namespace Sharpshooter.Controllers
{
    public class MenuItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MenuItems
        public ActionResult Index()
        {
            var menuItems = db.MenuItems.Include(m => m.Menu).Include(m => m.MenuGroup);
            return View(menuItems.ToList());
        }

        public ActionResult ViewMenuItems()
        {
            var menuItems = db.MenuItems.Include(m => m.Menu).Include(m => m.MenuGroup);
            return View(menuItems.ToList());
        }

        // GET: MenuItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            return View(menuItem);
        }

        // GET: MenuItems/Create
        public ActionResult Create()
        {
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle");
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle");
            return View();
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuItemID,MenuID,MenuGroupID,MenuItemTitle,MenuItemDescription,MenuItemNutrition,MenuItemIngredients,MenuItemQuantity,MenuItemImg,ImageFile,MenuItemCost")] MenuItem menuItem/*, HttpPostedFileBase MenuItemImg*/)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(menuItem.ImageFile.FileName);
                string extension = Path.GetExtension(menuItem.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                menuItem.MenuItemImg = "~/Content/ItemImages/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/ItemImages/"), fileName);
                menuItem.ImageFile.SaveAs(fileName);



                //MenuItem m = new MenuItem();
                //m.MenuItemTitle = menuItem.MenuItemTitle;
                //m.MenuItemImg = MenuItemImg.FileName.ToString();

                //var path = Server.MapPath("~/Content/ItemImages/");
                //MenuItemImg.SaveAs(Path.Combine(path, MenuItemImg.FileName.ToString()));

                db.MenuItems.Add(menuItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // GET: MenuItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuItemID,MenuID,MenuGroupID,MenuItemTitle,MenuItemDescription,MenuItemNutrition,MenuItemIngredients,MenuItemQuantity,MenuItemImg,ImageFile,MenuItemCost")] MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(menuItem.ImageFile.FileName);
                string extension = Path.GetExtension(menuItem.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                menuItem.MenuItemImg = "~/Content/ItemImages/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/ItemImages/"), fileName);
                menuItem.ImageFile.SaveAs(fileName);


                db.Entry(menuItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // GET: MenuItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            return View(menuItem);
        }

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuItem menuItem = db.MenuItems.Find(id);
            db.MenuItems.Remove(menuItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Views/MenuGroups/Create.cshtml
@model Sharpshooter.Models.MenuGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuGroupTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuGroupTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuGroupDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuGroupDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharpshooter/Views/MenuGroups/Delete.cshtml
@model Sharpshooter.Models.MenuGroup

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroupDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroupDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sharpshooter/Views/MenuGroups/Details.cshtml
@model Sharpshooter.Models.MenuGroup

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MenuGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroupDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroupDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MenuGroupID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sharpshooter/Views/MenuGroups/Edit.cshtml
@model Sharpshooter.Models.MenuGroup

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenuGroupID)

        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuGroupTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuGroupTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuGroupDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuGroupDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharpshooter/Views/MenuGroups/Index.cshtml
@model IEnumerable<Sharpshooter.Models.MenuGroup>

@{
    ViewBag.Title = "Admin Menu Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Menu Groups</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroupTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroupDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Menu.MenuTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuGroupTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuGroupDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MenuGroupID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MenuGroupID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MenuGroupID })
        </td>
    </tr>
}

</table>

<p>
    <li>@Html.ActionLink("Menu Items", "Index", "MenuItems")</li>
</p>

Sharpshooter/Views/MenuGroups/ViewMenuGroups.cshtml
@model IEnumerable<Sharpshooter.Models.MenuGroup>

@{
    ViewBag.Title = "Menu Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Menu Groups</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroupTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroupDescription)
        </th>
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Menu.MenuTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuGroupTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuGroupDescription)
        </td>
        
    </tr>
}

</table>